### PR TITLE
[WIP] Docker debuggable container + instruction + some fixes

### PR DESCRIPTION
**Pull request by noisy**
To start debug docker container, first dev container has to be build:

    docker-compose -f dev.yml build
    docker-compose -f debug.yml up

Next, fallow instructions from 

{{cookiecutter.repo_name}}/compose/pycharm/README.md

TODO:
* [x] - docker files are deleted at the end, if user don't want to use docker
* [ ] - delete unnecessary packages from `compose/pycharm/Dockerfile`
* [ ] - add information about repository https://github.com/tehsphinx/docker_pycharm_python which I use as base

### CODE REVIEW

**Comment by noisy** [comment]
@jayfk what do you think about that?

**Comment by jayfk** [comment]
That's great! I'll try it as soon as possible. I'm definitely very interested in this since I'm a PyCharm user myself.

I'm currently refactoring some parts of my initial configuration to get this merged in the upstream branch of `cookiecutter-django`.

**Comment by jayfk** [comment]
Could you rebase on the latest commit and maybe take a look at the changes?

**Comment by noisy** [comment]
I have noticed, that you PR was merged, so I close this one and I will prepare PR to pydanny/cookiecutter-django

**Comment by jayfk** [comment]
:+1:

**Pull request closed without merging**
